apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pokerfoci-ui
  name: pokerfoci-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pokerfoci-ui
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/pof-default: "true"
        io.kompose.service: pokerfoci-ui
    spec:
      containers:
        - image: dezsovargadev/pokerfoci-ui:0.0.2
          name: pokerfoci-ui
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_API_URL
                  name: pokerfoci-config
          ports:
            - containerPort: 3000
      restartPolicy: Always
