apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pokerfoci-ui
  name: pokerfoci-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pokerfoci-ui
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/pof-default: "true"
        io.kompose.service: pokerfoci-ui
    spec:
      containers:
        - image: dezsovargadev/pokerfoci-ui:latest
          name: pokerfoci-ui
          env:
            - name: REACT_APP_API_URL
              value: 'http://34.28.171.131:8081'
          ports:
            - containerPort: 3000
      restartPolicy: Always
